export const TW_UUIDS = {
    MAPITEMTYPE_TEST: 'mapitemtype-test@ddnet.tw',
    MAPITEMTYPE_AUTOMAPPER_CONFIG: 'mapitemtype-automapper-config@ddnet.tw',
    MAPITEMTYPE_ENVPOINTS_BEZIER: 'mapitemtype-envpoints-bezier@ddnet.tw',

    NETMSG_CAPABILITIES: 'capabilities@ddnet.tw',
    NETMSG_CHECKSUM_ERROR: 'checksum-error@ddnet.tw',
    NETMSG_CHECKSUM_REQUEST: 'checksum-request@ddnet.tw',
    NETMSG_CHECKSUM_RESPONSE: 'checksum-response@ddnet.tw',
    NETMSG_CLIENTVER: 'clientver@ddnet.tw',
    NETMSG_IDONTKNOW: 'i-dont-know@ddnet.tw',
    NETMSG_ITIS: 'it-is@ddnet.tw',
    NETMSG_MAPLIST_ADD: 'sv-maplist-add@ddnet.org',
    NETMSG_MAPLIST_GROUP_END: 'sv-maplist-end@ddnet.org',
    NETMSG_MAPLIST_GROUP_START: 'sv-maplist-start@ddnet.org',
    NETMSG_MAP_DETAILS: 'map-details@ddnet.tw',
    NETMSG_MAP_RELOAD: 'map-reload@ddnet.org',
    NETMSG_PINGEX: 'ping@ddnet.tw',
    NETMSG_PONGEX: 'pong@ddnet.tw',
    NETMSG_RCONTYPE: 'rcon-type@ddnet.tw',
    NETMSG_RCON_CMD_GROUP_END: 'rcon-cmd-group-end@ddnet.org',
    NETMSG_RCON_CMD_GROUP_START: 'rcon-cmd-group-start@ddnet.org',
    NETMSG_RECONNECT: 'reconnect@ddnet.org',
    NETMSG_REDIRECT: 'redirect@ddnet.org',
    NETMSG_WHATIS: 'what-is@ddnet.tw',

    TEEHISTORIAN_ANTIBOT: 'teehistorian-antibot@ddnet.org',
    TEEHISTORIAN_AUTH_INIT: 'teehistorian-auth-init@ddnet.tw',
    TEEHISTORIAN_AUTH_LOGIN: 'teehistorian-auth-login@ddnet.tw',
    TEEHISTORIAN_AUTH_LOGOUT: 'teehistorian-auth-logout@ddnet.tw',
    TEEHISTORIAN_DDNETVER: 'teehistorian-ddnetver@ddnet.tw',
    TEEHISTORIAN_DDNETVER_OLD: 'teehistorian-ddnetver-old@ddnet.tw',
    TEEHISTORIAN_JOINVER6: 'teehistorian-joinver6@ddnet.tw',
    TEEHISTORIAN_JOINVER7: 'teehistorian-joinver7@ddnet.tw',
    TEEHISTORIAN_LOAD_FAILURE: 'teehistorian-load-failure@ddnet.tw',
    TEEHISTORIAN_LOAD_SUCCESS: 'teehistorian-load-success@ddnet.tw',
    TEEHISTORIAN_PLAYER_FINISH: 'teehistorian-player-finish@ddnet.org',
    TEEHISTORIAN_PLAYER_NAME: 'teehistorian-player-name@ddnet.org',
    TEEHISTORIAN_PLAYER_READY: 'teehistorian-player-ready@ddnet.tw',
    TEEHISTORIAN_PLAYER_REJOIN: 'teehistorian-rejoinver6@ddnet.org',
    TEEHISTORIAN_PLAYER_SWITCH: 'teehistorian-player-swap@ddnet.tw',
    TEEHISTORIAN_PLAYER_TEAM: 'teehistorian-player-team@ddnet.tw',
    TEEHISTORIAN_SAVE_FAILURE: 'teehistorian-save-failure@ddnet.tw',
    TEEHISTORIAN_SAVE_SUCCESS: 'teehistorian-save-success@ddnet.tw',
    TEEHISTORIAN_TEAM_FINISH: 'teehistorian-team-finish@ddnet.org',
    TEEHISTORIAN_TEAM_PRACTICE: 'teehistorian-team-practice@ddnet.tw',
    TEEHISTORIAN_TEST: 'teehistorian-test@ddnet.tw',
} as const;

// неуверен в них